development:
  secret_key_base: ~~~~~~~~
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  payjp_key: <%= ENV["PAYJP_KEY"] %>
  payjp_private_key: <%= ENV["PAYJP_PRIVATE_KEY"] %>

  test:
  secret_key_base: ~~~~~~~~
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  payjp_key: <%= ENV["PAYJP_KEY"] %>
  payjp_private_key: <%= ENV["PAYJP_PRIVATE_KEY"] %>
  basic_auth_user: <%= ENV["BASIC_AUTH_USER"] %>
  basic_auth_password: <%= ENV["BASIC_AUTH_PASSWORD"] %>
